services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ires-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassw0rd!2026"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ires_sqlserver_data:/var/opt/mssql

volumes:
  ires_sqlserver_data: